INFRA: Initialize Acceptance Tests
Mums-Who-Code/ArtGallery.Services pull request #23
Opened 2021-11-18 02:39 UTC by NaynaMallick

Closes #22

2021-11-18 04:36 UTC, ShriHumrudha requested changes

2021-11-18 04:36 UTC, ShriHumrudha commented on ArtGallery.Services.Api.Tests.Acceptance/Apis/Home/HomeApiTests.Logic.cs
> +using System.Threading.Tasks;
Run code clean up

2021-11-18 04:36 UTC, ShriHumrudha commented on ArtGallery.Services.Api.Tests.Acceptance/Apis/Home/HomeApiTests.Logic.cs
> +
remove extra line.

2021-11-18 04:36 UTC, ShriHumrudha commented on ArtGallery.Services.Api.Tests.Acceptance/Apis/Home/HomeApiTests.cs
> +        public HomeApiTests(ArtGalleryApiBroker artGalleryApiBroker) =>
Need a new line space.

2021-11-18 04:36 UTC, ShriHumrudha commented on ArtGallery.Services.Api.Tests.Acceptance/ArtGallery.Services.Api.Tests.Acceptance.csproj
> +
Remove extra line

2021-11-18 04:36 UTC, ShriHumrudha commented on ArtGallery.Services.Api.Tests.Acceptance/Brokers/ArtGalleryApiBroker.Home.cs
> +
remove extra line.

2021-11-18 05:42 UTC, NaynaMallick commented on ArtGallery.Services.Api.Tests.Acceptance/Apis/Home/HomeApiTests.Logic.cs
> +using System.Threading.Tasks;
resolved

2021-11-18 05:43 UTC, NaynaMallick commented on ArtGallery.Services.Api.Tests.Acceptance/Apis/Home/HomeApiTests.Logic.cs
> +
resolved

2021-11-18 16:33 UTC, ShriHumrudha approved these changes

2021-11-19 18:42 UTC, Shrabanac approved these changes

2021-11-19 18:47 UTC, merged