DATA: User Model & Seeding
Mums-Who-Code/ArtGallery.Services pull request #33
Opened 2021-11-30 05:02 UTC by NaynaMallick

Closes #32

2021-11-30 06:30 UTC, ShriHumrudha requested changes

2021-11-30 06:30 UTC, ShriHumrudha commented on ArtGallery.Services.Api/Brokers/Storages/StorageBroker.User.Seeds.cs
> +                Id = System.Guid.Parse("c3a817cb-1528-4e30-81c0-389297978dc8"),
Move the System to the using statement.

2021-11-30 06:58 UTC, NaynaMallick commented on ArtGallery.Services.Api/Brokers/Storages/StorageBroker.User.Seeds.cs
> +                Id = System.Guid.Parse("c3a817cb-1528-4e30-81c0-389297978dc8"),
Modified

2021-11-30 18:40 UTC, ShriHumrudha approved these changes

2021-12-01 01:42 UTC, Shrabanac approved these changes

2021-12-01 01:55 UTC, merged