FOUNDATIONS: Add Artist
Mums-Who-Code/ArtGallery.Services pull request #39
Opened 2022-02-09 04:04 UTC by NaynaMallick

2022-02-13 20:58 UTC, ShriHumrudha requested changes

2022-02-13 20:58 UTC, ShriHumrudha commented on ArtGallery.Services.Api/Models/Artists/Exceptions/ArtistDependencyException.cs
> +            : base(message: "Artist Dependency error occured, contract support.", innerException)
small d

2022-02-13 20:58 UTC, ShriHumrudha commented on ArtGallery.Services.Api/Models/Artists/Exceptions/ArtistValidationException.cs
> +            : base(message: "Please fix the error and try again.", innerException)
Messaging to be more specific - Artist validation error occurred.

2022-02-13 20:58 UTC, ShriHumrudha commented on ArtGallery.Services.Api/Models/Artists/Exceptions/FailedArtistStorageException.cs
> +            : base(message: "Failed Artist Storage error occured.", innerException)
small letter - artist and storage

2022-02-13 20:58 UTC, ShriHumrudha commented on ArtGallery.Services.Api/Services/Foundations/Artists/ArtistService.Exceptions.cs
> +            var artistValidationDependencyException = new ArtistDependencyValidationException(exception);
Correct the variable name

2022-02-13 20:58 UTC, ShriHumrudha commented on ArtGallery.Services.Tests.Unit/Services/Foundations/Artists/ArtistServiceTests.Exceptions.Add.cs
> +                broker.LogError(It.Is(SameExceptionAs(expectedArtistDepdendencyValidationException))),
Move the variable to next line.

2022-02-13 20:58 UTC, ShriHumrudha commented on ArtGallery.Services.Tests.Unit/Services/Foundations/Artists/ArtistServiceTests.Exceptions.Add.cs
> +            var failedStorageDependencyException =
Update variable name

2022-02-13 20:58 UTC, ShriHumrudha commented on ArtGallery.Services.Tests.Unit/Services/Foundations/Artists/ArtistServiceTests.Exceptions.Add.cs
> +                this.artistService.AddArtistAsync(randomArtist);
someArtist is preferred to keep it consistent

2022-02-13 20:58 UTC, ShriHumrudha commented on ArtGallery.Services.Tests.Unit/Services/Foundations/Artists/ArtistServiceTests.Validations.Add.cs
> +                    SameExceptionAs(expectedArtistValidationException))),
Move 'SameExceptionAs' to above

2022-02-13 20:58 UTC, ShriHumrudha commented on ArtGallery.Services.Tests.Unit/Services/Foundations/Artists/ArtistServiceTests.Validations.Add.cs
> +            this.storageBrokerMock.VerifyNoOtherCalls();
Missing date time broker. Check in other tests as well.

2022-02-13 20:58 UTC, ShriHumrudha commented on ArtGallery.Services.Tests.Unit/Services/Foundations/Artists/ArtistServiceTests.cs
> +        private static Expression<Func<Xeption, bool>> SameExceptionAs(Exception expectedException)
Parameter type - Xeption

2022-02-13 22:33 UTC, NaynaMallick commented on ArtGallery.Services.Api/Models/Artists/Exceptions/ArtistDependencyException.cs
> +            : base(message: "Artist Dependency error occured, contract support.", innerException)
fixed

2022-02-13 22:36 UTC, NaynaMallick commented on ArtGallery.Services.Api/Models/Artists/Exceptions/ArtistValidationException.cs
> +            : base(message: "Please fix the error and try again.", innerException)
fixed

2022-02-13 22:37 UTC, NaynaMallick commented on ArtGallery.Services.Api/Models/Artists/Exceptions/FailedArtistStorageException.cs
> +            : base(message: "Failed Artist Storage error occured.", innerException)
fixed

2022-02-13 22:39 UTC, NaynaMallick commented on ArtGallery.Services.Api/Services/Foundations/Artists/ArtistService.Exceptions.cs
> +            var artistValidationDependencyException = new ArtistDependencyValidationException(exception);
done

2022-02-13 23:44 UTC, ShriHumrudha requested changes

2022-02-13 23:44 UTC, ShriHumrudha commented on ArtGallery.Services.Api/Startup.cs
> +            services.AddTransient<IArtistService, ArtistService>();
Single lie so you can do it =>

2022-02-13 23:44 UTC, ShriHumrudha commented on ArtGallery.Services.Tests.Unit/Services/Foundations/Artists/ArtistServiceTests.Exceptions.Add.cs
> +                    Times.Once);
Tab needed here

2022-02-15 06:05 UTC, ShriHumrudha approved these changes

2022-02-15 18:22 UTC, merged