DOCUMENTATION: Update README file
Mums-Who-Code/ArtGallery.Services pull request #7
Opened 2021-11-08 04:59 UTC by NaynaMallick

closes #6

2021-11-08 05:43 UTC, ShriHumrudha commented
Do upload the image too.

2021-11-08 05:43 UTC, ShriHumrudha requested changes
Do upload the image too.

2021-11-08 06:06 UTC, NaynaMallick commented
Uploaded image file.

2021-11-08 19:33 UTC, ShriHumrudha requested changes

2021-11-08 19:33 UTC, ShriHumrudha commented on README.md
> +  <img width="25%" height="25%" src="https://github.com/Mums-Who-Code/Random.Services/blob/main/artgallery.jpg">
Update the path

2021-11-08 22:35 UTC, Shrabanac approved these changes

2021-11-09 02:12 UTC, ShriHumrudha approved these changes

2021-11-09 02:15 UTC, merged